### ISSUE TITLE
Saving Data.

### ISSUE THREAD

**Issue by gwennie-chan** [Alice-Cheshire/Dynasty-Thingifier#6] opened 2017-11-07 05:49 UTC
Honestly the script is having data-saving problems again. Is it possible we could go back to the local storage database Tampermonkey provides? That would seem easier.

**Comment by Alice-Cheshire** [comment] 2017-11-08 04:38
I'm not sure what issue you're having but there shouldn't be any since it's using your browser's local storage now. We switched to this because Tampermonkey's local storage database stuff wouldn't cooperate. It flat out refused to load some values for seemingly no reason at all.

**Comment by Alice-Cheshire** [comment] 2017-11-22 22:51
https://dynasty-scans.com/forum/posts/330806

Closing this since it seems like this isn't actually a Thingifier bug.

**Closed as completed by Alice-Cheshire** 2017-11-22 22:51 UTC

**Comment by gwennie-chan** [comment] 2017-12-30 17:18
I remade my entire firefox profile a-new. Loaded up the scripts, and Thingifier still doesn't save data after exiting Firefox and re-opening it. I tested this on Windows 7 64-bit with Firefox 58.0b13

**Comment by Alice-Cheshire** [comment] 2018-01-01 03:12
I'm really not sure what your problem could be. I use Firefox's stable release stream on 64-bit Windows 10 and things work perfectly fine for me. What addons do you have installed?

**Comment by gwennie-chan** [comment] 2018-01-02 00:41
I have Tampermonkey (naturally), Stylus, Yomi-chan, uBlock Origin, Duck Duck Go Plus, and New Xkit for Tumblr.

**Comment by Alice-Cheshire** [comment] 2018-01-03 01:42
Tampermonkey, Stylus, and uBlock Origin are three I use myself so they definitely can't be the cause. Xkit shouldn't be the issue since that's for Tumblr and I tested Yomi-chan since I wasn't sure on that one and it has no issue on my end. Duck Duck Go Plus appears to be a Ghostery alternative so I haven't tested it but I don't believe that should cause issues either.

**Comment by gwennie-chan** [comment] 2018-01-03 03:01
Did you test on FF 58 beta?

**Comment by Alice-Cheshire** [comment] 2018-01-04 04:40
No, I don't really bother with beta versions unless they're major updates. (Quantum, for example.) If it was an issue with the FF58 beta specifically then it's almost certainly a bug with that version of the browser.
